name: david dew bruner
favicon: null
layout_spectrum: 0.6982621566858143
typography_spectrum: 0.7656372070778161
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4108503258321434
  lightness: 0.7080481555312872
  saturation: 0.0441190549172461
  rhythmicContrast: 0.5550622323062271
purpose: []
